#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
OUTPUT_FILE="$ROOT_DIR/Setup.sh"
DIST_DIR="$ROOT_DIR/dist"
DIST_FILE="$DIST_DIR/Setup.sh"
TMP_FILE="$(mktemp)"

LIB_FILES=(
  "$ROOT_DIR/src/lib/core.sh"
  "$ROOT_DIR/src/lib/ui.sh"
  "$ROOT_DIR/src/lib/registry.sh"
)

cleanup() {
  rm -f "$TMP_FILE"
}

trap cleanup EXIT

generate_embedded_assets() {
  local asset_file
  local asset_key
  local delimiter

  cat <<'EOF'
write_embedded_asset() {
  local asset_key="$1"
  local output_path="$2"

  case "$asset_key" in
EOF

  while IFS= read -r asset_file; do
    asset_key="${asset_file#"$ROOT_DIR/src/assets/"}"
    delimiter="__SETUP_ASSET_$(printf '%s' "$asset_key" | tr '/.-' '_')__"

    printf '    "%s")\n' "$asset_key"
    printf '      cat >"$output_path" <<'\''%s'\''\n' "$delimiter"
    cat "$asset_file"
    printf '\n%s\n' "$delimiter"
    cat <<'EOF'
      ;;
EOF
  done < <(find "$ROOT_DIR/src/assets" -type f | sort)

  cat <<'EOF'
    *)
      warn "未找到内置资源：$asset_key"
      return 1
      ;;
  esac
}
EOF
}

{
  cat <<'EOF'
#!/usr/bin/env bash
# This file is generated by scripts/build.sh. Do not edit directly.

set -o pipefail

EOF

  printf 'SETUP_SERVER_BUILD_AT=%q\n\n' "$(date -u '+%Y-%m-%dT%H:%M:%SZ')"

  for lib_file in "${LIB_FILES[@]}"; do
    cat "$lib_file"
    printf '\n'
  done

  generate_embedded_assets
  printf '\n'

  while IFS= read -r module_file; do
    cat "$module_file"
    printf '\n'
  done < <(find "$ROOT_DIR/src/modules" -type f -name '*.sh' | sort)

  cat "$ROOT_DIR/src/entry.sh"
} >"$TMP_FILE"

bash -n "$TMP_FILE"
chmod +x "$TMP_FILE"
mkdir -p "$DIST_DIR"
cp "$TMP_FILE" "$OUTPUT_FILE"
cp "$TMP_FILE" "$DIST_FILE"

printf 'Built %s and %s\n' "$OUTPUT_FILE" "$DIST_FILE"
