# FastTracker 2 .xm module player in Javascript
# Deployment path: /root/docker-compose/jsxm/docker-compose.yml

services:
  fsxm:
    image: tsanfer/jsxm:latest
    container_name: jsxm
    ports:
      - 8081:8080
    restart: unless-stopped
