# Web 服务器
# 部署目录：/root/docker-compose/nginx/docker-compose.yml

services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./html:/usr/share/nginx/html:ro # 网站根目录
    ports:
      - 80:80 # Web 端口
    restart: always
