# 订阅转换后端
# 部署目录：/root/docker-compose/subconverter/docker-compose.yml

services:
  subconverter:
    container_name: subconverter
    image: tindy2013/subconverter
    ports:
      - 25500:25500
    restart: always
