# 在线 web 目标识别
# 部署目录：/root/docker-compose/web_object_detection/docker-compose.yml

services:
  object_detection:
    image: tsanfer/web_object_detection
    container_name: object_detection
    ports:
      - 4000:4000 # Web 后端
      - 8000:8000 # Web 前端
    restart: unless-stopped
